"""
ResolveX Early Warning & Emerging Issue Endpoints
Provides operational anomaly detection scans, active early warning feeds,
and transition into Phase 4 incident investigation.
"""

from typing import List, Optional, Dict, Any
from fastapi import APIRouter, HTTPException, status, Query, Body

from apps.api.app.domain.schemas import (
    ApiResponse,
    ApiErrorResponse,
    EarlyWarningSchema
)
from apps.api.app.services.anomaly_engine import anomaly_engine

router = APIRouter(tags=["Early Warnings & Anomalies"])

@router.get("/early-warnings", response_model=ApiResponse[List[EarlyWarningSchema]])
async def list_early_warnings(
    status: Optional[str] = Query(None, description="NEW, INVESTIGATING, LINKED_TO_INCIDENT, DISMISSED, RESOLVED"),
    severity: Optional[str] = Query(None, description="critical, high, medium, low")
):
    """Lists active early warnings generated by the operational anomaly detector"""
    warnings = await anomaly_engine.list_early_warnings(status=status, severity=severity)
    return ApiResponse(data=warnings, meta={"total": len(warnings)})

@router.get("/early-warnings/{warning_id}", response_model=ApiResponse[EarlyWarningSchema], responses={404: {"model": ApiErrorResponse}})
async def get_early_warning_detail(warning_id: str):
    """Retrieves detailed operational telemetry and evidence for an early warning"""
    w = await anomaly_engine.get_early_warning(warning_id)
    if not w:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"code": "EARLY_WARNING_NOT_FOUND", "message": f"Early warning '{warning_id}' not found."}
        )
    return ApiResponse(data=w)

@router.post("/incidents/detect-emerging", response_model=ApiResponse[List[EarlyWarningSchema]])
async def trigger_emerging_issues_scan():
    """Triggers real-time statistical anomaly scan across service events and telemetry"""
    warnings = await anomaly_engine.detect_emerging_issues()
    return ApiResponse(data=warnings, meta={"scanned": True, "active_warnings": len(warnings)})

@router.post("/early-warnings/{warning_id}/investigate", response_model=ApiResponse[Dict[str, Any]], responses={404: {"model": ApiErrorResponse}})
async def investigate_early_warning(warning_id: str):
    """Transitions an early warning into active investigation or links to an incident"""
    success, message, payload = await anomaly_engine.investigate_early_warning(warning_id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"code": "EARLY_WARNING_NOT_FOUND", "message": message}
        )
    return ApiResponse(data=payload or {}, meta={"message": message})

@router.post("/early-warnings/{warning_id}/dismiss", response_model=ApiResponse[Dict[str, Any]], responses={404: {"model": ApiErrorResponse}})
async def dismiss_early_warning(
    warning_id: str,
    reason: Optional[str] = Body(None, embed=True)
):
    """Dismisses an early warning as transient noise or verified benign variation"""
    success, message = await anomaly_engine.dismiss_early_warning(warning_id, reason=reason or "")
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"code": "EARLY_WARNING_NOT_FOUND", "message": message}
        )
    return ApiResponse(data={"warning_id": warning_id, "status": "DISMISSED"}, meta={"message": message})
